version: '3.0'

services:
  bartcode-frontend:
    image: bkielczewski/bartcode-frontend:master
    ports:
      - 4000:4000
    volumes:
      - ./data:/data
    links:
      - bartcode-service
    restart: unless-stopped

  bartcode-service:
    image: bkielczewski/bartcode-service:master
    ports:
      - 8080:8080
    volumes:
      - ./data:/app/data
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped
